version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 500 --reload
    volumes:
      - ./app:/app
    ports:
      - "500:500"
    # depends_on:
    #   - rabbitmq
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   env_file:
  #     - ./.env
  #   environment:
  #     - PYTHONPATH=/

  # consumer:
  #   build:
  #     context: ./consumer
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./consumer:/consumer
  #     - ./app:/consumer/app
  #   depends_on:
  #     - rabbitmq
  #   env_file:
  #     - ./.env
  #   environment:
  #     - PYTHONPATH=/consumer:/consumer/app
